remote_theme: pmarsceill/just-the-docs

name: Inteligencia Artificial
title: Inteligencia Artifical
description: Notas para el exámen de admisión para la maestria en Inteligencia Artificial en la Universidad Veracruzana.
#baseurl: "/Inteligencia Artificial" # the subpath of your site, e.g. /blog
#url: "https://baldeadr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Adrián Daniel Balderas Mijes

# Aux links for the upper right navigation
aux_links:
  "Fork me on GitHub":
    - "//github.com/baldeadr/Inteligencia-Artifical"
    - <button class="btn js-toggle-dark-mode">Preview dark color scheme</button>
    - <script type="text/javascript" src="{{ "/assets/js/dark-mode-preview.js" | absolute_url }}"></script>
# Color scheme currently only supports "dark" or nil (default)
#color_scheme: "dark"

