remote_theme: pmarsceill/just-the-docs

title: Inteligencia Artifical
description: Notas para el exámen de admisión para la maestria en Inteligencia Artificial en la Universidad Veracruzana.
baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog
url: "https://baldeadr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Color scheme currently only supports "dark" or nil (default)
#color_scheme: "dark"

